sudo: required

env:
  - book="core" stylename="github" exportdir="gh-pages"

before_install:
  - git clone https://github.com/wiztigers/docgen.git docgen
  - chmod +x docgen/setup.sh docgen/docgen.py
  - ./docgen/setup.sh sass ${stylename}

script:
  - [ -d ${exportdir} ] || mkdir ${exportdir}
  - cp README.adoc ${exportdir}
  - cp -r resources ${exportdir}/resources
  - cp "sass/stylesheets/${stylename}.css" "${exportdir}/${stylename}.css"
  - mkdir -p "${exportdir}/images";
  - cp -r "sass/images/${stylename}" "${exportdir}/images/${stylename}";
  - sed -i.tmp  -e "s/..\/images\/$stylename/.\/images\/$stylename/g" "${exportdir}/${stylename}.css";
  - rm "${exportdir}/${stylename}.css.tmp";
  - ./docgen/docgen.py --html --input ${book}.adoc  --output index.html --outdir gh-pages --stylename ${stylename} --stylesdir sass --linkstyle
  - ./docgen/docgen.py --pdf  --input gh-pages/index.html --output ${book}.pdf   --outdir gh-pages

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  local-dir: gh-pages
  on:
    branch: master
