sudo: required

env:
  - stylename="wizdom" exportdir="gh-pages"

before_install:
  - git clone https://github.com/wiztigers/docgen.git docgen
  - chmod +x docgen/setup.sh docgen/docgen.py
  - ./docgen/setup.sh sass ${stylename}

script:
  - mkdir ${exportdir}
  - cp -r ./docgen/www/* ${exportdir}
  - cp -r ./www/* ${exportdir}
  - cp -r resources ${exportdir}
  - cp README.adoc ${exportdir}
  - ./docgen/docgen.py --html --input core.adoc               --output index.html                  --outdir ${exportdir}    --stylename ${stylename} --stylesdir sass --linkstyle
  - ./docgen/docgen.py --pdf  --input ${exportdir}/index.html --output InteractionHommeMachine.pdf --outdir ${exportdir}
  - ./docgen/docgen.py --html --input TP/Qt.adoc              --output Qt.html                     --outdir ${exportdir}/TP --stylename ${stylename}
  - ./docgen/docgen.py --html --input TP/Qt-QGraphics.adoc    --output Qt-QGraphics.html           --outdir ${exportdir}/TP --stylename ${stylename}
  - ./docgen/docgen.py --html --input TP/web.adoc             --output Web.html                    --outdir ${exportdir}/TP --stylename ${stylename}

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  local-dir: gh-pages
  on:
    branch: master
