sudo: required

env:
  - stylename="wizdom" exportdir="gh-pages"

before_install:
  - git clone https://github.com/wiztigers/docgen.git docgen
  - chmod +x docgen/setup.sh docgen/docgen.py
  - ./docgen/setup.sh sass ${stylename}

script:
  - ./docgen/docgen.py --html --input core.adoc  --output index.html --outdir gh-pages --stylename ${stylename} --stylesdir sass --linkstyle
  - ./docgen/docgen.py --pdf  --input gh-pages/index.html --output InteractionHommeMachine.pdf   --outdir gh-pages
  - cp -r ./docgen/www/* ${exportdir}
  - cp -r ./www/* ${exportdir}
  - cp -r resources ${exportdir}
  - cp README.adoc ${exportdir}

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  local-dir: gh-pages
  on:
    branch: master
